[tool.poetry]
name = "repl_python3_magic-firewall"
version = "0.1.0"
description = ""
authors = ["RootFinder <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pysimplegui = "^4.40.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
